gesture = {
    0: 'middle_finger',
    1: 'heart',
    2: 'heart_twohands',
    3: 'thumb_up',
    4: 'v',
    5: 'ok',
    6: 'call',
    7: 'alien',
    8: 'baby',
    9: 'four',
    10: 'mandoo',
    11: 'one',
    12: 'rabbit',
    13: 'rock',
    14: 'three',
    15: 'two',
    16: 'eight',
    17: 'five',
    18: 'lucky_finger',
    19: 'seven',
    20: 'six',
    21: 'wolf',
}